name: CraftGuard
main: fr.frozentux.craftguard.CraftGuardPlugin
version: 1.3.1
commands:
   cg:
      description: Reload config.
      usage: /cg <args>
      permission: craftguard.admin
      permisison-message: You can't do that